name: nike_store_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
# firebase
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0

  #splash screen
  animated_splash_screen: ^1.3.0

  # storages
  shared_preferences: ^2.2.2

  #icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0

  #state management
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  dartz: ^0.10.1
  
  flutter:
    sdk: flutter
  
  # for UI
  getwidget: ^4.0.0
  smooth_page_indicator: ^1.1.0

  #responsive
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  
  # Fonts:

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Bold.ttf
        - asset: fonts/Raleway-SemiBold.ttf
  
